name: idealadder
favicon: null
layout_spectrum: 0.9058276969008148
typography_spectrum: 0.32054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77787b'
    - '#ed1651'
    - '#000000'
    - '#ffffff'
    - '#00ff00'
  brandStrength: 0.3125
  lightness: 0.5577014570590109
  saturation: 0.23161003086715937
  rhythmicContrast: 0.8635714424308389
purpose: []
